import 'package:flutter/foundation.dart';

class Genres with ChangeNotifier {
  // static const _genres = [
  //   "acoustic",
  //   "afrobeat",
  //   "alt-rock",
  //   "alternative",
  //   "ambient",
  //   "anime",
  //   "black-metal",
  //   "bluegrass",
  //   "blues",
  //   "bossanova",
  //   "brazil",
  //   "breakbeat",
  //   "british",
  //   "cantopop",
  //   "chicago-house",
  //   "children",
  //   "chill",
  //   "classical",
  //   "club",
  //   "comedy",
  //   "country",
  //   "dance",
  //   "dancehall",
  //   "death-metal",
  //   "deep-house",
  //   "detroit-techno",
  //   "disco",
  //   "disney",
  //   "drum-and-bass",
  //   "dub",
  //   "dubstep",
  //   "edm",
  //   "electro",
  //   "electronic",
  //   "emo",
  //   "folk",
  //   "forro",
  //   "french",
  //   "funk",
  //   "garage",
  //   "german",
  //   "gospel",
  //   "goth",
  //   "grindcore",
  //   "groove",
  //   "grunge",
  //   "guitar",
  //   "happy",
  //   "hard-rock",
  //   "hardcore",
  //   "hardstyle",
  //   "heavy-metal",
  //   "hip-hop",
  //   "holidays",
  //   "honky-tonk",
  //   "house",
  //   "idm",
  //   "indian",
  //   "indie",
  //   "indie-pop",
  //   "industrial",
  //   "iranian",
  //   "j-dance",
  //   "j-idol",
  //   "j-pop",
  //   "j-rock",
  //   "jazz",
  //   "k-pop",
  //   "kids",
  //   "latin",
  //   "latino",
  //   "malay",
  //   "mandopop",
  //   "metal",
  //   "metal-misc",
  //   "metalcore",
  //   "minimal-techno",
  //   "movies",
  //   "mpb",
  //   "new-age",
  //   "new-release",
  //   "opera",
  //   "pagode",
  //   "party",
  //   "philippines-opm",
  //   "piano",
  //   "pop",
  //   "pop-film",
  //   "post-dubstep",
  //   "power-pop",
  //   "progressive-house",
  //   "psych-rock",
  //   "punk",
  //   "punk-rock",
  //   "r-n-b",
  //   "rainy-day",
  //   "reggae",
  //   "reggaeton",
  //   "road-trip",
  //   "rock",
  //   "rock-n-roll",
  //   "rockabilly",
  //   "romance",
  //   "sad",
  //   "salsa",
  //   "samba",
  //   "sertanejo",
  //   "show-tunes",
  //   "singer-songwriter",
  //   "ska",
  //   "sleep",
  //   "songwriter",
  //   "soul",
  //   "soundtracks",
  //   "spanish",
  //   "study",
  //   "summer",
  //   "swedish",
  //   "synth-pop",
  //   "tango",
  //   "techno",
  //   "trance",
  //   "trip-hop",
  //   "turkish",
  //   "work-out",
  //   "world-music"
  // ];
  static const _genres = <String>[
    "21st century classical",
    "432hz",
    "8-bit",
    "a cappella",
    "aarhus indie",
    "aberdeen indie",
    "abstract",
    "abstract beats",
    "abstract hip hop",
    "abstract idm",
    "abstractro",
    "accordeon",
    "accordion",
    "acid house",
    "acid idm",
    "acid jazz",
    "acid rock",
    "acid techno",
    "acid trance",
    "acousmatic",
    "acoustic blues",
    "acoustic chill",
    "acoustic opm",
    "acoustic pop",
    "acoustic punk",
    "action rock",
    "adelaide indie",
    "adoracao",
    "adoracion",
    "adult standards",
    "adventista",
    "afghan pop",
    "afghan traditional",
    "african electronic",
    "african experimental",
    "african gospel",
    "african metal",
    "african percussion",
    "african reggae",
    "african rock",
    "afrikaans",
    "afrikaans folk",
    "afrikaans gospel",
    "afro dancehall",
    "afro house",
    "afro psych",
    "afro-funk",
    "afrobeat",
    "afrobeat brasileiro",
    "afrofuturism",
    "afrofuturismo brasileiro",
    "afropop",
    "aggro chileno",
    "aggrotech",
    "aghani lil-atfal",
    "alabama indie",
    "alabama metal",
    "alabama rap",
    "alaska indie",
    "albanian folk",
    "albanian hip hop",
    "albanian pop",
    "albany ny indie",
    "alberta country",
    "alberta hip hop",
    "album rock",
    "albuquerque indie",
    "algerian folk",
    "alphorn",
    "alpine yodeling",
    "alt-idol",
    "alternative americana",
    "alternative ccm",
    "alternative country",
    "alternative dance",
    "alternative emo",
    "alternative hardcore",
    "alternative hip hop",
    "alternative metal",
    "alternative metalcore",
    "alternative pop",
    "alternative pop rock",
    "alternative r&b",
    "alternative rock",
    "alternative roots rock",
    "amapiano",
    "ambeat",
    "ambient",
    "ambient black metal",
    "ambient dub techno",
    "ambient folk",
    "ambient fusion",
    "ambient house",
    "ambient idm",
    "ambient industrial",
    "ambient psychill",
    "ambient techno",
    "ambient worship",
    "american 21st century classical",
    "american choir",
    "american contemporary classical",
    "american folk revival",
    "american metalcore",
    "american modern classical",
    "american post-rock",
    "american primitive",
    "american romanticism",
    "american shoegaze",
    "amharic pop",
    "anadolu rock",
    "anarcho-punk",
    "ancient mediterranean",
    "andalusian classical",
    "andean",
    "andean flute",
    "anglican liturgy",
    "animal singing",
    "anime",
    "anime cv",
    "anime latino",
    "anime rock",
    "anime score",
    "ann arbor indie",
    "anthem",
    "anthem emo",
    "anthem worship",
    "anti-folk",
    "antideutsche",
    "antiviral pop",
    "appalachian folk",
    "appenzeller folk",
    "arab alternative",
    "arab electronic",
    "arab folk",
    "arab groove",
    "arab metal",
    "arab pop",
    "arab trap",
    "arabesk",
    "arabic hip hop",
    "arabic jazz",
    "argentine alternative rock",
    "argentine ambient",
    "argentine hardcore",
    "argentine heavy metal",
    "argentine hip hop",
    "argentine indie",
    "argentine indie rock",
    "argentine jazz",
    "argentine metal",
    "argentine punk",
    "argentine reggae",
    "argentine rock",
    "argentine telepop",
    "arkansas country",
    "arkansas indie",
    "armenian folk",
    "armenian pop",
    "arpa paraguaya",
    "art pop",
    "art punk",
    "art rock",
    "asbury park indie",
    "asheville indie",
    "asmr",
    "assyrian pop",
    "athens indie",
    "atl hip hop",
    "atl trap",
    "atlanta indie",
    "atmosphere",
    "atmospheric black metal",
    "atmospheric dnb",
    "atmospheric doom",
    "atmospheric post-metal",
    "atmospheric post-rock",
    "atmospheric sludge",
    "auckland indie",
    "audiophile vocal",
    "aussie drill",
    "aussie emo",
    "aussietronica",
    "austin americana",
    "austin hip hop",
    "austin rock",
    "austindie",
    "australian alternative pop",
    "australian alternative rock",
    "australian americana",
    "australian black metal",
    "australian blues",
    "australian children's music",
    "australian choir",
    "australian classical",
    "australian comedy",
    "australian country",
    "australian dance",
    "australian electropop",
    "australian garage punk",
    "australian hardcore",
    "australian hip hop",
    "australian house",
    "australian indie",
    "australian indie folk",
    "australian indie rock",
    "australian indigenous",
    "australian jazz",
    "australian metal",
    "australian metalcore",
    "australian pop",
    "australian post-hardcore",
    "australian post-punk",
    "australian post-rock",
    "australian psych",
    "australian r&b",
    "australian reggae fusion",
    "australian rock",
    "australian rockabilly",
    "australian shoegaze",
    "australian singer-songwriter",
    "australian ska",
    "australian talent show",
    "australian trap",
    "australian underground hip hop",
    "austrian choir",
    "austrian contemporary classical",
    "austrian hip hop",
    "austrian indie",
    "austrian jazz",
    "austrian metal",
    "austrian pop",
    "austrian stoner rock",
    "austrian techno",
    "austro-german modernism",
    "austropop",
    "autoharp",
    "autonomous black metal",
    "avant-garde",
    "avant-garde black metal",
    "avant-garde jazz",
    "avant-garde metal",
    "avant-rock",
    "axe",
    "azeri pop",
    "azeri traditional",
    "azonto",
    "azontobeats",
    "bachata",
    "background music",
    "backing track",
    "bagpipe",
    "bahai",
    "bahamian folk",
    "bahamian pop",
    "baile pop",
    "baithak gana",
    "baja indie",
    "bajki",
    "bakersfield sound",
    "balafon",
    "balalaika",
    "balearic",
    "balfolk",
    "balkan brass",
    "balkan hip hop",
    "balkan trap",
    "ballet class",
    "ballroom",
    "baltic black metal",
    "baltic choir",
    "baltic classical",
    "baltic folk",
    "baltimore hip hop",
    "baltimore indie",
    "baluchi folk",
    "band organ",
    "banda",
    "banda caliente",
    "banda carnavalera",
    "bandinhas",
    "bandoneon",
    "bangla",
    "banjo",
    "bansuri",
    "baptist gospel",
    "barbadian pop",
    "barbershop",
    "bard",
    "barnalog",
    "barnemusikk",
    "barnmusik",
    "barnsagor",
    "baroque",
    "baroque ensemble",
    "baroque pop",
    "baroque singing",
    "baroque violin",
    "basel indie",
    "basque folk",
    "bass house",
    "bass music",
    "bass trap",
    "bass trip",
    "basshall",
    "bassline",
    "batak",
    "bath indie",
    "batida",
    "baton rouge indie",
    "baton rouge rap",
    "battle rap",
    "bay area hip hop",
    "bay area indie",
    "bayerischer rap",
    "bboy",
    "bc underground hip hop",
    "beach house",
    "beach music",
    "beat italiano",
    "beatboxing",
    "beatdown",
    "beats",
    "bebop",
    "bedroom pop",
    "bedroom soul",
    "belarusian electronic",
    "belarusian indie",
    "belarusian pop",
    "belarusian rock",
    "belarussian metal",
    "belfast indie",
    "belfast metal",
    "belgian black metal",
    "belgian blues",
    "belgian contemporary classical",
    "belgian dance",
    "belgian edm",
    "belgian experimental",
    "belgian hip hop",
    "belgian indie",
    "belgian indie rock",
    "belgian jazz",
    "belgian metal",
    "belgian modern jazz",
    "belgian new wave",
    "belgian pop",
    "belgian post-rock",
    "belgian punk",
    "belgian rock",
    "belgian singer-songwriter",
    "belgian stoner rock",
    "belgian techno",
    "bells",
    "belly dance",
    "belo horizonte indie",
    "bemani",
    "benga",
    "bengali folk",
    "beninese pop",
    "bergen indie",
    "berlin minimal techno",
    "berlin school",
    "bern indie",
    "bernu dziesmas",
    "bhangra",
    "bible",
    "big band",
    "big beat",
    "big room",
    "bikutsi",
    "binaural",
    "birdsong",
    "birmingham grime",
    "birmingham hip hop",
    "birmingham indie",
    "birmingham metal",
    "birthday",
    "bitpop",
    "black 'n' roll",
    "black comedy",
    "black death",
    "black metal",
    "black metal argentino",
    "black noise",
    "black sludge",
    "black thrash",
    "blackened crust",
    "blackened hardcore",
    "blackgaze",
    "blaskapelle",
    "blasmusik",
    "bleep techno",
    "bluegrass",
    "bluegrass gospel",
    "blues",
    "blues band",
    "blues latinoamericano",
    "blues rock",
    "blues-rock guitar",
    "bmore",
    "boeremusiek",
    "bohemian baroque",
    "bolero",
    "bolero cubano",
    "bolivian metal",
    "bolivian rock",
    "bongo flava",
    "boogaloo",
    "boogie-woogie",
    "boom bap",
    "bornesange",
    "bosnian electronic",
    "bosnian indie",
    "bossa nova",
    "bossa nova cover",
    "bossa nova jazz",
    "boston hardcore",
    "boston hip hop",
    "boston indie",
    "boston metal",
    "boston punk",
    "boston rock",
    "bothy ballad",
    "botswana pop",
    "bounce",
    "bouncy house",
    "bouzouki",
    "bow pop",
    "boy band",
    "boy pop",
    "boy soprano",
    "brain waves",
    "braindance",
    "brasilia hip hop",
    "brass band",
    "brass ensemble",
    "brass quintet",
    "brazilian black metal",
    "brazilian blues",
    "brazilian boogie",
    "brazilian ccm",
    "brazilian composition",
    "brazilian death metal",
    "brazilian doom metal",
    "brazilian edm",
    "brazilian emo",
    "brazilian experimental",
    "brazilian gospel",
    "brazilian grindcore",
    "brazilian hardcore",
    "brazilian hip hop",
    "brazilian house",
    "brazilian indie",
    "brazilian indie rock",
    "brazilian jazz",
    "brazilian lo-fi rock",
    "brazilian metal",
    "brazilian modern jazz",
    "brazilian neo-psychedelic",
    "brazilian percussion",
    "brazilian post-hardcore",
    "brazilian post-rock",
    "brazilian psychedelic",
    "brazilian punk",
    "brazilian punk rock",
    "brazilian reggae",
    "brazilian rock",
    "brazilian ska",
    "brazilian soul",
    "brazilian stoner rock",
    "brazilian surf rock",
    "brazilian techno",
    "brazilian thrash metal",
    "breakbeat",
    "breakcore",
    "breaks",
    "brega",
    "brega funk",
    "brega romantico",
    "breton folk",
    "brighton indie",
    "brill building pop",
    "brisbane indie",
    "bristol electronic",
    "bristol indie",
    "brit funk",
    "british alternative rock",
    "british black metal",
    "british blues",
    "british brass band",
    "british children's music",
    "british choir",
    "british comedy",
    "british contemporary classical",
    "british country",
    "british dance band",
    "british electroacoustic",
    "british experimental",
    "british folk",
    "british indie rock",
    "british industrial",
    "british invasion",
    "british jazz",
    "british math rock",
    "british modern classical",
    "british post-rock",
    "british singer-songwriter",
    "british soul",
    "british soundtrack",
    "britpop",
    "broadway",
    "broken beat",
    "bronx hip hop",
    "brooklyn indie",
    "brostep",
    "brutal death metal",
    "brutal deathcore",
    "bubble trance",
    "bubblegum dance",
    "bubblegum pop",
    "buffalo ny indie",
    "buffalo ny metal",
    "bulgarian electronic",
    "bulgarian folk",
    "bulgarian hip hop",
    "bulgarian indie",
    "bulgarian metal",
    "bulgarian pop",
    "bulgarian rock",
    "burkinabe pop",
    "burkinabe traditional",
    "burmese pop",
    "burmese traditional",
    "burundian traditional",
    "bury st edmunds indie",
    "byzantine",
    "c-pop",
    "c64",
    "c86",
    "cabaret",
    "cajun",
    "calgary indie",
    "cali rap",
    "calming instrumental",
    "calypso",
    "cambodian rock",
    "cambodian traditional",
    "cambridgeshire indie",
    "cameroonian pop",
    "canadian black metal",
    "canadian blues",
    "canadian ccm",
    "canadian celtic",
    "canadian children's music",
    "canadian choir",
    "canadian classical",
    "canadian comedy",
    "canadian contemporary country",
    "canadian contemporary r&b",
    "canadian country",
    "canadian electronic",
    "canadian electropop",
    "canadian experimental",
    "canadian folk",
    "canadian garage rock",
    "canadian hardcore",
    "canadian hip hop",
    "canadian house",
    "canadian indie",
    "canadian indigenous",
    "canadian latin",
    "canadian metal",
    "canadian metalcore",
    "canadian modern jazz",
    "canadian pop",
    "canadian pop punk",
    "canadian post-hardcore",
    "canadian post-punk",
    "canadian post-rock",
    "canadian psychedelic",
    "canadian psychedelic rock",
    "canadian punk",
    "canadian rock",
    "canadian rockabilly",
    "canadian shoegaze",
    "canadian singer-songwriter",
    "canadian soundtrack",
    "canadian stoner rock",
    "canberra indie",
    "cancion infantil mexicana",
    "cancion melodica",
    "cancoes infantis",
    "candombe",
    "candomble",
    "candy pop",
    "cantaditas",
    "cantautor",
    "cantautor catala",
    "cante alentejano",
    "cante flamenco",
    "canterbury scene",
    "canti alpini",
    "canto a tenore",
    "canto popular uruguayo",
    "cantonese traditional",
    "cantopop",
    "canzone d'autore",
    "canzone genovese",
    "canzone napoletana",
    "cape breton folk",
    "cape town indie",
    "cape verdean folk",
    "capoeira",
    "caracas indie",
    "cardiff indie",
    "caribbean metal",
    "carnatic",
    "carnatic instrumental",
    "carnatic vocal",
    "carnaval",
    "carnaval cadiz",
    "carnaval limburg",
    "cartoon",
    "catalan folk",
    "cathedral choir",
    "catstep",
    "caucasian folk",
    "cavernous death metal",
    "ccm",
    "cdmx indie",
    "cedm",
    "ceilidh",
    "cello",
    "celtic",
    "celtic harp",
    "celtic metal",
    "celtic punk",
    "celtic rock",
    "central asian folk",
    "cha-cha-cha",
    "chaabi algerien",
    "chaabi marocain",
    "chakra",
    "chalga",
    "chamame",
    "chamber choir",
    "chamber ensemble",
    "chamber orchestra",
    "chamber pop",
    "chamber psych",
    "champeta",
    "channel islands indie",
    "channel pop",
    "chanson",
    "chanson paillarde",
    "chanson quebecois",
    "chant basque",
    "chant religieux",
    "chaotic black metal",
    "chaotic hardcore",
    "charanga",
    "charango",
    "charlotte nc indie",
    "charlottesville indie",
    "charred death",
    "chattanooga indie",
    "chechen pop",
    "chicago blues",
    "chicago drill",
    "chicago hardcore",
    "chicago house",
    "chicago indie",
    "chicago pop punk",
    "chicago punk",
    "chicago rap",
    "chicago soul",
    "chicano punk",
    "chicano rap",
    "chicha",
    "chihuahua indie",
    "children's choir",
    "children's folk",
    "children's music",
    "children's story",
    "chilean black metal",
    "chilean hardcore",
    "chilean indie",
    "chilean metal",
    "chilean rock",
    "chill beats",
    "chill groove",
    "chill guitar",
    "chill lounge",
    "chill-out trance",
    "chillhop",
    "chillstep",
    "chillwave",
    "chinderlieder",
    "chinese audiophile",
    "chinese classical",
    "chinese classical performance",
    "chinese drama ost",
    "chinese electronic",
    "chinese electropop",
    "chinese experimental",
    "chinese folk",
    "chinese hip hop",
    "chinese idol pop",
    "chinese indie",
    "chinese indie rock",
    "chinese instrumental",
    "chinese jazz",
    "chinese metal",
    "chinese minyao",
    "chinese new year",
    "chinese opera",
    "chinese post-rock",
    "chinese punk",
    "chinese soundtrack",
    "chinese traditional",
    "chinese worship",
    "chip hop",
    "chiptune",
    "choral",
    "choro",
    "christchurch indie",
    "christelijk",
    "christian a cappella",
    "christian afrobeat",
    "christian alternative rock",
    "christian dance",
    "christian deathcore",
    "christian hard rock",
    "christian hardcore",
    "christian hip hop",
    "christian indie",
    "christian metal",
    "christian music",
    "christian pop",
    "christian power metal",
    "christian punk",
    "christian relaxative",
    "christian rock",
    "christian symphonic metal",
    "christian thrash metal",
    "christian trap",
    "christian uplift",
    "christlicher rap",
    "christmas instrumental",
    "christmas product",
    "chunchaca",
    "chutney",
    "cifteli",
    "cimbalom",
    "cincinnati indie",
    "cinematic dubstep",
    "cinematic post-rock",
    "circassian folk",
    "circuit",
    "circus",
    "classic afrobeat",
    "classic arab pop",
    "classic australian country",
    "classic belgian pop",
    "classic bollywood",
    "classic bulgarian pop",
    "classic canadian rock",
    "classic cantopop",
    "classic colombian pop",
    "classic country pop",
    "classic czech pop",
    "classic danish pop",
    "classic dutch pop",
    "classic eurovision",
    "classic finnish pop",
    "classic finnish rock",
    "classic french pop",
    "classic garage rock",
    "classic girl group",
    "classic greek pop",
    "classic greek rock",
    "classic icelandic pop",
    "classic indo pop",
    "classic iskelma",
    "classic israeli pop",
    "classic italian folk pop",
    "classic italian pop",
    "classic j-rock",
    "classic japanese jazz",
    "classic latvian pop",
    "classic luk thung",
    "classic malaysian pop",
    "classic mandopop",
    "classic moroccan pop",
    "classic nepali pop",
    "classic norwegian pop",
    "classic nz country",
    "classic nz pop",
    "classic opm",
    "classic pakistani pop",
    "classic persian pop",
    "classic peruvian pop",
    "classic polish pop",
    "classic portuguese pop",
    "classic praise",
    "classic progressive house",
    "classic psychedelic rock",
    "classic rock",
    "classic russian pop",
    "classic russian rock",
    "classic schlager",
    "classic sinhala pop",
    "classic soul",
    "classic soundtrack",
    "classic swedish pop",
    "classic thai pop",
    "classic tunisian pop",
    "classic turkish pop",
    "classic uk pop",
    "classic venezuelan pop",
    "classical",
    "classical accordion",
    "classical baritone",
    "classical bass",
    "classical bassoon",
    "classical cello",
    "classical clarinet",
    "classical contralto",
    "classical countertenor",
    "classical era",
    "classical flute",
    "classical guitar",
    "classical guitar duo",
    "classical guitar quartet",
    "classical harp",
    "classical horn",
    "classical mandolin",
    "classical mezzo-soprano",
    "classical oboe",
    "classical organ",
    "classical percussion",
    "classical performance",
    "classical piano",
    "classical piano duo",
    "classical piano trio",
    "classical saxophone",
    "classical saxophone quartet",
    "classical soprano",
    "classical string trio",
    "classical tenor",
    "classical trombone",
    "classical trumpet",
    "classical tuba",
    "classify",
    "clawhammer banjo",
    "clean comedy",
    "cleveland indie",
    "coco",
    "cocuk sarkilari",
    "coldwave",
    "collage pop",
    "college a cappella",
    "college marching band",
    "cologne electronic",
    "cologne indie",
    "colombian black metal",
    "colombian electronic",
    "colombian hardcore",
    "colombian hip hop",
    "colombian indie",
    "colombian pop",
    "colombian rock",
    "columbus ohio indie",
    "combos nacionales",
    "comedienne",
    "comedy",
    "comedy rap",
    "comedy rock",
    "comic",
    "comic metal",
    "commons",
    "complextro",
    "compositional ambient",
    "concepcion indie",
    "concert band",
    "concertina",
    "connecticut hardcore",
    "connecticut indie",
    "conscious hip hop",
    "contemporary classical",
    "contemporary classical piano",
    "contemporary country",
    "contemporary folk",
    "contemporary gospel",
    "contemporary jazz",
    "contemporary post-bop",
    "contemporary vocal jazz",
    "contrabass",
    "cook islands pop",
    "cool jazz",
    "copla",
    "coptic hymn",
    "cork indie",
    "cornetas y tambores",
    "cornish folk",
    "cornwall indie",
    "corrido",
    "corridos cristianos",
    "corrosion",
    "corsican folk",
    "cosmic american",
    "cosmic black metal",
    "cosmic post-rock",
    "cosmic uplifting trance",
    "country",
    "country blues",
    "country boogie",
    "country dawn",
    "country gospel",
    "country pop",
    "country quebecois",
    "country rap",
    "country road",
    "country rock",
    "coupe decale",
    "coventry indie",
    "coverchill",
    "covertrance",
    "cowboy western",
    "cowpunk",
    "crack rock steady",
    "croatian electronic",
    "croatian folk",
    "croatian indie",
    "croatian metal",
    "croatian pop",
    "croatian rock",
    "crossover prog",
    "crossover thrash",
    "crunk",
    "crust punk",
    "cryptic black metal",
    "cuarteto",
    "cuatro venezolano",
    "cuban alternative",
    "cuban electronic",
    "cuban rumba",
    "cubaton",
    "cueca chilena",
    "cuento infantile",
    "cumbia",
    "cumbia andina mexicana",
    "cumbia boliviana",
    "cumbia chilena",
    "cumbia ecuatoriana",
    "cumbia funk",
    "cumbia paraguaya",
    "cumbia peruana",
    "cumbia pop",
    "cumbia ranchera",
    "cumbia salvadorena",
    "cumbia santafesina",
    "cumbia sonidera",
    "cumbia surena",
    "cumbia uruguaya",
    "cumbia villera",
    "cyber metal",
    "cyberpunk",
    "cymraeg",
    "cypriot pop",
    "czech contemporary classical",
    "czech electronic",
    "czech folk",
    "czech hip hop",
    "czech indie",
    "czech metal",
    "czech pop",
    "czech punk",
    "czech rock",
    "czsk black metal",
    "czsk hip hop",
    "czsk reggae",
    "dabke",
    "dainuojamoji poezija",
    "dakke dak",
    "dallas indie",
    "dance pop",
    "dance rock",
    "dance-punk",
    "dancehall",
    "dangdut",
    "dangdut koplo",
    "dangdut remix",
    "danish alternative rock",
    "danish choir",
    "danish classical",
    "danish contemporary classical",
    "danish electro",
    "danish electronic",
    "danish electropop",
    "danish experimental",
    "danish folk",
    "danish hip hop",
    "danish indie",
    "danish indie pop",
    "danish jazz",
    "danish metal",
    "danish modern jazz",
    "danish pop",
    "danish pop rock",
    "danish singer-songwriter",
    "danish techno",
    "dansband",
    "danseband",
    "dansk lovsang",
    "dansktop",
    "danspunk",
    "darbuka",
    "dark ambient",
    "dark black metal",
    "dark cabaret",
    "dark disco",
    "dark electro",
    "dark electro-industrial",
    "dark hardcore",
    "dark jazz",
    "dark minimal techno",
    "dark post-punk",
    "dark progressive house",
    "dark psytrance",
    "dark techno",
    "dark trap",
    "dark wave",
    "darkstep",
    "darksynth",
    "dayton indie",
    "dc hardcore",
    "dc indie",
    "death 'n' roll",
    "death industrial",
    "death metal",
    "deathcore",
    "deathgrass",
    "deathgrind",
    "deathrock",
    "deathstep",
    "deep acoustic pop",
    "deep active rock",
    "deep adult standards",
    "deep ambient",
    "deep big room",
    "deep brazilian pop",
    "deep breakcore",
    "deep ccm",
    "deep chill",
    "deep chill-out",
    "deep christian rock",
    "deep classic garage rock",
    "deep comedy",
    "deep contemporary country",
    "deep cumbia sonidera",
    "deep dance pop",
    "deep darkpsy",
    "deep deep house",
    "deep deep tech house",
    "deep delta blues",
    "deep disco",
    "deep disco house",
    "deep discofox",
    "deep dnb",
    "deep downtempo fusion",
    "deep dubstep",
    "deep east coast hip hop",
    "deep euro house",
    "deep eurodance",
    "deep filthstep",
    "deep flow",
    "deep folk metal",
    "deep free jazz",
    "deep freestyle",
    "deep full on",
    "deep funk",
    "deep funk house",
    "deep funk ostentacao",
    "deep g funk",
    "deep german hip hop",
    "deep german indie",
    "deep german punk",
    "deep gothic post-punk",
    "deep groove house",
    "deep happy hardcore",
    "deep hardcore",
    "deep hardcore punk",
    "deep hardtechno",
    "deep house",
    "deep idm",
    "deep indian pop",
    "deep indie pop",
    "deep indie rock",
    "deep indie singer-songwriter",
    "deep italo disco",
    "deep jazz fusion",
    "deep latin alternative",
    "deep latin christian",
    "deep latin jazz",
    "deep liquid",
    "deep liquid bass",
    "deep melodic death metal",
    "deep melodic euro house",
    "deep melodic hard rock",
    "deep melodic metalcore",
    "deep metalcore",
    "deep minimal techno",
    "deep motown",
    "deep neo-synthpop",
    "deep neofolk",
    "deep new americana",
    "deep new wave",
    "deep norteno",
    "deep northern soul",
    "deep orgcore",
    "deep pop edm",
    "deep pop emo",
    "deep pop r&b",
    "deep power-pop punk",
    "deep progressive house",
    "deep progressive trance",
    "deep psychobilly",
    "deep psytrance",
    "deep punk rock",
    "deep r&b",
    "deep ragga",
    "deep rai",
    "deep regional mexican",
    "deep smooth jazz",
    "deep soft rock",
    "deep soul house",
    "deep soundtrack",
    "deep southern soul",
    "deep southern trap",
    "deep space rock",
    "deep sunset lounge",
    "deep surf music",
    "deep swedish rock",
    "deep symphonic black metal",
    "deep talent show",
    "deep tech house",
    "deep techno",
    "deep tropical house",
    "deep turkish pop",
    "deep underground hip hop",
    "deep uplifting trance",
    "deep vocal house",
    "deep vocal jazz",
    "delaware indie",
    "delta blues",
    "dembow",
    "demoscene",
    "denpa-kei",
    "denton tx indie",
    "denver indie",
    "denver rap",
    "depressive black metal",
    "derby indie",
    "derry indie",
    "desert blues",
    "desi hip hop",
    "desi pop",
    "destroy techno",
    "detroit hip hop",
    "detroit house",
    "detroit indie",
    "detroit techno",
    "detroit trap",
    "detske pisnicky",
    "detski pesnichki",
    "detskie pesni",
    "deutsch disney",
    "devon indie",
    "dfw rap",
    "dhrupad",
    "didgeridoo",
    "digital hardcore",
    "dinner jazz",
    "dirty south rap",
    "dirty texas rap",
    "disco",
    "disco house",
    "disco polo",
    "discofox",
    "disney",
    "disney espanol",
    "disney italiano",
    "disney portugues",
    "disney portugues brasil",
    "disney svenska",
    "diva house",
    "dixieland",
    "diy emo",
    "diy pop punk",
    "dizi",
    "djembe",
    "djent",
    "dmv rap",
    "dombra",
    "dominican indie",
    "dominican pop",
    "dong-yo",
    "doo-wop",
    "doom metal",
    "doomcore",
    "dortmund indie",
    "doujin",
    "downtempo",
    "downtempo fusion",
    "draaiorgel",
    "dragspel",
    "drama",
    "dream pop",
    "dream trance",
    "dreamgaze",
    "dreamo",
    "dresden indie",
    "drift",
    "drill",
    "drill and bass",
    "drone",
    "drone ambient",
    "drone folk",
    "drone metal",
    "drone psych",
    "dronescape",
    "drum and bass",
    "drumfunk",
    "dub",
    "dub metal",
    "dub product",
    "dub reggae",
    "dub techno",
    "dublin indie",
    "dubstep",
    "dubstep product",
    "dubsteppe",
    "duduk",
    "duluth indie",
    "dundee indie",
    "dunedin indie",
    "dunedin sound",
    "dungeon synth",
    "duranguense",
    "dusseldorf electronic",
    "dusseldorf indie",
    "dutch americana",
    "dutch black metal",
    "dutch blues",
    "dutch cabaret",
    "dutch contemporary classical",
    "dutch death metal",
    "dutch disney",
    "dutch drill",
    "dutch edm",
    "dutch experimental",
    "dutch experimental electronic",
    "dutch folk",
    "dutch hip hop",
    "dutch house",
    "dutch idol pop",
    "dutch indie",
    "dutch indie rock",
    "dutch jazz",
    "dutch metal",
    "dutch musical",
    "dutch pop",
    "dutch prog",
    "dutch punk",
    "dutch punk rock",
    "dutch r&b",
    "dutch rock",
    "dutch singer-songwriter",
    "dutch tech house",
    "dutch trap",
    "dutch underground hip hop",
    "dutch urban",
    "dweilorkest",
    "e6fi",
    "early avant garde",
    "early french punk",
    "early modern classical",
    "early music",
    "early music choir",
    "early music ensemble",
    "early reggae",
    "early romantic era",
    "early us punk",
    "east anglia indie",
    "east coast hip hop",
    "east coast reggae",
    "eastern bloc groove",
    "easy listening",
    "easycore",
    "eau claire indie",
    "ebm",
    "ecm-style jazz",
    "ectofolk",
    "ecuadorian alternative rock",
    "ecuadorian indie",
    "ecuadorian pop",
    "edinburgh indie",
    "edinburgh metal",
    "edm",
    "edmonton indie",
    "egyptian hip hop",
    "egyptian pop",
    "egyptian traditional",
    "el paso indie",
    "electra",
    "electric bass",
    "electric blues",
    "electro",
    "electro bailando",
    "electro dub",
    "electro house",
    "electro jazz",
    "electro latino",
    "electro swing",
    "electro trash",
    "electro-industrial",
    "electroacoustic composition",
    "electroacoustic improvisation",
    "electroclash",
    "electrofox",
    "electronic djent",
    "electronic rock",
    "electronic trap",
    "electronica",
    "electronica argentina",
    "electronica cristiana",
    "electronicore",
    "electropop",
    "electropowerpop",
    "elektropunk",
    "emo",
    "emo punk",
    "emo rap",
    "emocore",
    "emoviolence",
    "english baroque",
    "english indie rock",
    "english renaissance",
    "enka",
    "entehno",
    "environmental",
    "epic doom",
    "epicore",
    "er ge",
    "erhu",
    "eritrean pop",
    "erotica",
    "escape room",
    "esperanto",
    "essex indie",
    "estonian electronic",
    "estonian folk",
    "estonian hip hop",
    "estonian indie",
    "estonian jazz",
    "estonian metal",
    "estonian pop",
    "estonian rock",
    "ethereal gothic",
    "ethereal wave",
    "etherpop",
    "ethio-jazz",
    "ethiopian pop",
    "ethnomusicology",
    "ethnotronica",
    "euphonium",
    "euphoric hardstyle",
    "euro hi-nrg",
    "eurobeat",
    "eurodance",
    "europop",
    "euroska",
    "eurovision",
    "euskal indie",
    "euskal metal",
    "euskal rock",
    "exotica",
    "experimental",
    "experimental ambient",
    "experimental bass",
    "experimental big band",
    "experimental black metal",
    "experimental club",
    "experimental dubstep",
    "experimental electronic",
    "experimental folk",
    "experimental hip hop",
    "experimental house",
    "experimental indie",
    "experimental jazz",
    "experimental percussion",
    "experimental poetry",
    "experimental pop",
    "experimental psych",
    "experimental rock",
    "experimental synth",
    "experimental techno",
    "experimental vocal",
    "fado",
    "fake",
    "fallen angel",
    "family gospel",
    "faroese folk",
    "faroese indie",
    "faroese jazz",
    "faroese pop",
    "faroese rock",
    "fast melodic punk",
    "fidget house",
    "field recording",
    "fijian pop",
    "filmi",
    "filter house",
    "filthstep",
    "final fantasy",
    "fingerstyle",
    "finnish black metal",
    "finnish blues",
    "finnish choir",
    "finnish classical",
    "finnish dance pop",
    "finnish death metal",
    "finnish doom metal",
    "finnish edm",
    "finnish electro",
    "finnish electronic",
    "finnish folk",
    "finnish hardcore",
    "finnish hip hop",
    "finnish indie",
    "finnish jazz",
    "finnish metal",
    "finnish pop",
    "finnish psychedelic rock",
    "finnish punk",
    "finnish reggae",
    "finnish rockabilly",
    "finnish tango",
    "finnish techno",
    "finnish worship",
    "firenze indie",
    "fisarmonica",
    "flamenco",
    "flamenco guitar",
    "flemish folk",
    "flick hop",
    "float house",
    "florida death metal",
    "florida hardcore",
    "florida rap",
    "fluxwork",
    "fo jing",
    "focus",
    "focus trance",
    "folclor afrocolombiano",
    "folclor colombiano",
    "folclore castilla y leon",
    "folclore extremeno",
    "folclore portugues",
    "folk",
    "folk brasileiro",
    "folk cantabria",
    "folk metal",
    "folk metal latinoamericano",
    "folk punk",
    "folk rock",
    "folk rock italiano",
    "folk siciliana",
    "folk-pop",
    "folklore argentino",
    "folklore boliviano",
    "folklore chileno",
    "folklore ecuatoriano",
    "folklore nuevo argentino",
    "folklore panameno",
    "folklore paraguayo",
    "folklore peruano",
    "folklore quebecois",
    "folklore venezolano",
    "folkmusik",
    "folktronica",
    "football",
    "footwork",
    "forest psy",
    "forro",
    "forro tradicional",
    "fort worth indie",
    "fourth world",
    "franco-flemish school",
    "francoton",
    "frankfurt electronic",
    "frankfurt indie",
    "freak folk",
    "freakbeat",
    "free folk",
    "free improvisation",
    "free jazz",
    "freestyle",
    "fremantle indie",
    "french baroque",
    "french black metal",
    "french contemporary classical",
    "french death metal",
    "french dub",
    "french folk",
    "french folk pop",
    "french hip hop",
    "french indie pop",
    "french indietronica",
    "french jazz",
    "french metal",
    "french movie tunes",
    "french opera",
    "french pop",
    "french post-punk",
    "french post-rock",
    "french punk",
    "french reggae",
    "french renaissance",
    "french rock",
    "french shoegaze",
    "french soundtrack",
    "french techno",
    "french worship",
    "frenchcore",
    "fuji",
    "full on",
    "funana",
    "funeral doom",
    "funk",
    "funk bh",
    "funk carioca",
    "funk das antigas",
    "funk evangelico",
    "funk metal",
    "funk ostentacao",
    "funk rock",
    "funky breaks",
    "funky tech house",
    "fussball",
    "future ambient",
    "future funk",
    "future garage",
    "future house",
    "future rock",
    "futurepop",
    "g funk",
    "gabba",
    "gabonese pop",
    "gaian doom",
    "gainesville indie",
    "gaita",
    "gaita zuliana",
    "galante era",
    "galego",
    "galician folk",
    "galician indie",
    "galician jazz",
    "galician rock",
    "galway indie",
    "gamecore",
    "gamelan",
    "gaming edm",
    "gangster rap",
    "garage pop",
    "garage psych",
    "garage punk",
    "garage punk blues",
    "garage rock",
    "garifuna folk",
    "gauze pop",
    "gbvfi",
    "geek folk",
    "geek rock",
    "gengetone",
    "georgian polyphony",
    "georgiana",
    "german alternative rap",
    "german alternative rock",
    "german baroque",
    "german black metal",
    "german blues",
    "german ccm",
    "german choir",
    "german cloud rap",
    "german contemporary classical",
    "german country",
    "german dance",
    "german dark minimal techno",
    "german electronica",
    "german hard rock",
    "german hardcore",
    "german hip hop",
    "german house",
    "german indie",
    "german indie folk",
    "german indie pop",
    "german indie rock",
    "german jazz",
    "german literature",
    "german metal",
    "german metalcore",
    "german oi",
    "german opera",
    "german pop",
    "german pop rock",
    "german post-hardcore",
    "german post-punk",
    "german post-rock",
    "german punk",
    "german punk rock",
    "german reggae",
    "german renaissance",
    "german rock",
    "german rockabilly",
    "german shoegaze",
    "german show tunes",
    "german singer-songwriter",
    "german ska",
    "german soundtrack",
    "german stoner rock",
    "german street punk",
    "german tech house",
    "german techno",
    "german thrash metal",
    "german trap",
    "german underground rap",
    "german worship",
    "ghanaian gospel",
    "ghanaian hip hop",
    "ghanaian pop",
    "ghanaian traditional",
    "ghazal",
    "ghent indie",
    "ghettotech",
    "ghoststep",
    "girl group",
    "glam metal",
    "glam punk",
    "glam rock",
    "glasgow indie",
    "glass",
    "glee club",
    "glitch",
    "glitch beats",
    "glitch hop",
    "glitch pop",
    "glitter trance",
    "gnawa",
    "go-go",
    "goa psytrance",
    "goa trance",
    "goralski",
    "goregrind",
    "gospel",
    "gospel blues",
    "gospel italiano",
    "gospel r&b",
    "gospel rap",
    "gospel reggae",
    "gospel singers",
    "gothabilly",
    "gothenburg hip hop",
    "gothenburg indie",
    "gothenburg metal",
    "gothic alternative",
    "gothic americana",
    "gothic doom",
    "gothic metal",
    "gothic post-punk",
    "gothic rock",
    "gothic symphonic metal",
    "gqom",
    "granada indie",
    "grand rapids indie",
    "grave wave",
    "graz indie",
    "greek black metal",
    "greek clarinet",
    "greek contemporary classical",
    "greek folk",
    "greek guitar",
    "greek hip hop",
    "greek house",
    "greek indie",
    "greek metal",
    "greek pop",
    "greek rock",
    "greek swing",
    "greek trap",
    "greenlandic pop",
    "grim death metal",
    "grime",
    "grime brasileiro",
    "grimewave",
    "grindcore",
    "griot",
    "grisly death metal",
    "groove metal",
    "groove room",
    "grunge",
    "grunge pop",
    "grupera",
    "gruperas inmortales",
    "guadalajara indie",
    "guam indie",
    "guaracha",
    "guatemalan indie",
    "guatemalan metal",
    "guatemalan pop",
    "guggenmusik",
    "guidance",
    "guided meditation",
    "guinean pop",
    "guitar case",
    "guitarra argentina",
    "guitarra portuguesa",
    "gulf hip hop",
    "gumbe",
    "guqin",
    "guzheng",
    "gwoka",
    "gymcore",
    "gypsy",
    "gypsy fusion",
    "gypsy jazz",
    "gypsy punk",
    "haitian dance",
    "haitian gospel",
    "haitian traditional",
    "halifax indie",
    "halloween",
    "hamburg electronic",
    "hamburg hip hop",
    "hamburg indie",
    "hamburger schule",
    "hamilton on indie",
    "hammered dulcimer",
    "hammond organ",
    "hampton roads indie",
    "handbells",
    "hands up",
    "hangpan",
    "happy hardcore",
    "hard alternative",
    "hard bass",
    "hard bop",
    "hard chime",
    "hard dance",
    "hard glam",
    "hard house",
    "hard minimal techno",
    "hard rock",
    "hard rock brasileiro",
    "hard stoner rock",
    "hard techno",
    "hard trance",
    "hardcore",
    "hardcore breaks",
    "hardcore hip hop",
    "hardcore punk",
    "hardcore punk espanol",
    "hardcore techno",
    "hardingfele",
    "hardstyle",
    "hardvapour",
    "harlem hip hop",
    "harmonica blues",
    "harmonica jazz",
    "harmonikka",
    "harp",
    "harpsichord",
    "hauntology",
    "hawaiian",
    "hawaiian hip hop",
    "hawaiian indie",
    "hawaiian punk",
    "healing",
    "heartland rock",
    "heavy alternative",
    "heavy gothic rock",
    "heavy psych",
    "hi-nrg",
    "hi-tech",
    "highlife",
    "himalayan folk",
    "hindi hip hop",
    "hindi worship",
    "hindustani classical",
    "hindustani instrumental",
    "hindustani vocal",
    "hip hop",
    "hip hop cubano",
    "hip hop galsen",
    "hip hop quebecois",
    "hip hop tuga",
    "hip house",
    "hip pop",
    "hiplife",
    "histoire pour enfants",
    "historic classical performance",
    "historic orchestral performance",
    "historic piano performance",
    "historical keyboard",
    "historically informed performance",
    "hmong pop",
    "hoerspiel",
    "hokkien pop",
    "hollywood",
    "hong kong hip hop",
    "hong kong indie",
    "honky tonk",
    "honky-tonk piano",
    "hopebeat",
    "horror punk",
    "horror synth",
    "horrorcore",
    "house",
    "house argentino",
    "houston indie",
    "houston rap",
    "huapango",
    "huayno",
    "huayno popular",
    "hula",
    "hull indie",
    "hungarian contemporary classical",
    "hungarian hip hop",
    "hungarian indie",
    "hungarian metal",
    "hungarian pop",
    "hungarian punk",
    "hungarian rock",
    "hungarian underground rap",
    "hurdy-gurdy",
    "hyperpop",
    "hyphy",
    "hypnosis",
    "icelandic choir",
    "icelandic classical",
    "icelandic electronic",
    "icelandic experimental",
    "icelandic folk",
    "icelandic hip hop",
    "icelandic indie",
    "icelandic jazz",
    "icelandic metal",
    "icelandic pop",
    "icelandic rock",
    "icelandic traditional",
    "idaho indie",
    "idol",
    "idol rock",
    "igbo traditional",
    "igbo worship",
    "ilahiler",
    "illbient",
    "ilocano pop",
    "indian classical",
    "indian edm",
    "indian electronic",
    "indian folk",
    "indian indie",
    "indian jazz",
    "indian metal",
    "indian rock",
    "indian techno",
    "indian violin",
    "indiana indie",
    "indie anthem-folk",
    "indie cafe pop",
    "indie cantabria",
    "indie catala",
    "indie cordoba",
    "indie curitibano",
    "indie deutschrap",
    "indie dream pop",
    "indie electronica",
    "indie electropop",
    "indie emo",
    "indie emo rock",
    "indie extremena",
    "indie folk",
    "indie folk argentino",
    "indie folk italiano",
    "indie fuzzpop",
    "indie game soundtrack",
    "indie garage rock",
    "indie jazz",
    "indie liguria",
    "indie napoletano",
    "indie nordeste argentino",
    "indie platense",
    "indie pop",
    "indie pop rap",
    "indie pop rock",
    "indie poptimism",
    "indie psych-pop",
    "indie psychedelic rock",
    "indie punk",
    "indie quebecois",
    "indie r&b",
    "indie rock",
    "indie rock italiano",
    "indie rockism",
    "indie salvadoreno",
    "indie shoegaze",
    "indie siciliano",
    "indie singer-songwriter",
    "indie soul",
    "indie surf",
    "indie tico",
    "indie valenciana",
    "indie veneto",
    "indie viet",
    "indiecoustica",
    "indietronica",
    "indonesian bamboo",
    "indonesian black metal",
    "indonesian city pop",
    "indonesian death metal",
    "indonesian edm",
    "indonesian electronic",
    "indonesian folk",
    "indonesian hardcore",
    "indonesian hip hop",
    "indonesian idol pop",
    "indonesian indie",
    "indonesian indie pop",
    "indonesian indie rock",
    "indonesian jazz",
    "indonesian metal",
    "indonesian pop",
    "indonesian pop punk",
    "indonesian post-hardcore",
    "indonesian psychedelia",
    "indonesian punk",
    "indonesian r&b",
    "indonesian reggae",
    "indonesian rock",
    "indonesian worship",
    "indorock",
    "industrial",
    "industrial black metal",
    "industrial hip hop",
    "industrial metal",
    "industrial rock",
    "industrial techno",
    "indy indie",
    "instrumental acoustic guitar",
    "instrumental bluegrass",
    "instrumental death metal",
    "instrumental funk",
    "instrumental grime",
    "instrumental math rock",
    "instrumental post-rock",
    "instrumental progressive metal",
    "instrumental rock",
    "instrumental soul",
    "instrumental stoner rock",
    "instrumental surf",
    "intelligent dance music",
    "inuit pop",
    "inuit traditional",
    "iowa indie",
    "iranian experimental",
    "iraqi pop",
    "irish accordion",
    "irish ballad",
    "irish banjo",
    "irish classical",
    "irish contemporary classical",
    "irish country",
    "irish dance",
    "irish electronic",
    "irish fiddle",
    "irish flute",
    "irish folk",
    "irish gaelic folk",
    "irish hip hop",
    "irish indie",
    "irish indie rock",
    "irish metal",
    "irish neo-traditional",
    "irish pop",
    "irish pub song",
    "irish rebel song",
    "irish rock",
    "irish singer-songwriter",
    "irish techno",
    "iskelma",
    "islamic recitation",
    "isle of man indie",
    "isle of wight indie",
    "israeli classical",
    "israeli folk",
    "israeli hip hop",
    "israeli indie",
    "israeli jazz",
    "israeli mediterranean",
    "israeli metal",
    "israeli pop",
    "israeli rock",
    "israeli singer-songwriter",
    "israeli techno",
    "israeli trap",
    "italian alternative",
    "italian arena pop",
    "italian baritone",
    "italian baroque",
    "italian bass",
    "italian black metal",
    "italian blues",
    "italian choir",
    "italian contemporary classical",
    "italian contemporary jazz",
    "italian death metal",
    "italian disco",
    "italian doom metal",
    "italian electronica",
    "italian emo",
    "italian experimental",
    "italian folk",
    "italian folk metal",
    "italian gothic",
    "italian gothic metal",
    "italian hardcore",
    "italian hip hop",
    "italian indie pop",
    "italian industrial",
    "italian jazz",
    "italian jazz fusion",
    "italian library music",
    "italian mandolin",
    "italian metal",
    "italian metalcore",
    "italian mezzo-soprano",
    "italian modern prog",
    "italian new wave",
    "italian occult psychedelia",
    "italian opera",
    "italian pop",
    "italian pop punk",
    "italian pop rock",
    "italian post punk",
    "italian post-hardcore",
    "italian post-rock",
    "italian power metal",
    "italian progressive metal",
    "italian progressive rock",
    "italian punk",
    "italian reggae",
    "italian renaissance",
    "italian rockabilly",
    "italian ska",
    "italian soprano",
    "italian soundtrack",
    "italian stoner rock",
    "italian tech house",
    "italian techno",
    "italian tenor",
    "italian underground hip hop",
    "italo beats",
    "italo dance",
    "italo house",
    "italogaze",
    "j-acoustic",
    "j-ambient",
    "j-core",
    "j-dance",
    "j-division",
    "j-idol",
    "j-indie",
    "j-metal",
    "j-pixie",
    "j-pop",
    "j-pop boy group",
    "j-pop girl group",
    "j-poprock",
    "j-punk",
    "j-rap",
    "j-reggae",
    "j-rock",
    "jacksonville indie",
    "jam band",
    "jamgrass",
    "jamtronica",
    "jangle pop",
    "jangle rock",
    "japanese alternative rock",
    "japanese black metal",
    "japanese chillhop",
    "japanese choir",
    "japanese city pop",
    "japanese classical",
    "japanese classical performance",
    "japanese concert band",
    "japanese death metal",
    "japanese disney",
    "japanese dream pop",
    "japanese electronic",
    "japanese electropop",
    "japanese emo",
    "japanese experimental",
    "japanese folk",
    "japanese garage rock",
    "japanese girl punk",
    "japanese hardcore",
    "japanese heavy metal",
    "japanese idm",
    "japanese indie folk",
    "japanese indie pop",
    "japanese indie rock",
    "japanese instrumental",
    "japanese jazz",
    "japanese jazz fusion",
    "japanese jazztronica",
    "japanese math rock",
    "japanese melodic punk",
    "japanese metalcore",
    "japanese new wave",
    "japanese pop punk",
    "japanese post-hardcore",
    "japanese post-punk",
    "japanese post-rock",
    "japanese power metal",
    "japanese prog",
    "japanese progressive house",
    "japanese psychedelic",
    "japanese psychedelic rock",
    "japanese punk rock",
    "japanese r&b",
    "japanese rockabilly",
    "japanese shoegaze",
    "japanese singer-songwriter",
    "japanese ska",
    "japanese soul",
    "japanese soundtrack",
    "japanese techno",
    "japanese traditional",
    "japanese trap",
    "japanese vgm",
    "japanese vocal jazz",
    "japanese worship",
    "japanoise",
    "jaw harp",
    "jawaiian",
    "jazz",
    "jazz accordion",
    "jazz blues",
    "jazz boom bap",
    "jazz brass",
    "jazz caraibes",
    "jazz catala",
    "jazz chileno",
    "jazz clarinet",
    "jazz colombiano",
    "jazz composition",
    "jazz cubano",
    "jazz double bass",
    "jazz drums",
    "jazz flute",
    "jazz funk",
    "jazz fusion",
    "jazz guitar",
    "jazz harp",
    "jazz metal",
    "jazz mexicano",
    "jazz orchestra",
    "jazz organ",
    "jazz piano",
    "jazz quartet",
    "jazz rap",
    "jazz rock",
    "jazz saxophone",
    "jazz trio",
    "jazz trombone",
    "jazz trumpet",
    "jazz tuba",
    "jazz venezolano",
    "jazz vibraphone",
    "jazz violin",
    "jazztronica",
    "jersey club",
    "jewish a capella",
    "jewish cantorial",
    "jewish hip hop",
    "jewish pop",
    "jig and reel",
    "jordanian pop",
    "joropo",
    "jovem guarda",
    "judaica",
    "jug band",
    "jugendchor",
    "jump blues",
    "jump up",
    "jumpstyle",
    "jumptek",
    "jungle",
    "junior eurovision",
    "k-hop",
    "k-indie",
    "k-pop",
    "k-pop boy group",
    "k-pop girl group",
    "k-rock",
    "kaba gaida",
    "kabarett",
    "kabyle",
    "kaneka",
    "kannada bhava geethe",
    "kansas indie",
    "kantele",
    "kapa haka",
    "karadeniz halk muzigi",
    "karaoke",
    "karneval",
    "kaseko",
    "kashmiri pop",
    "kavkaz",
    "kawaii edm",
    "kawaii future bass",
    "kawaii metal",
    "kayokyoku",
    "kazakh pop",
    "kc indie",
    "kelowna bc indie",
    "kent indie",
    "kentucky indie",
    "kentucky metal",
    "kentucky mountain folk",
    "kenyan pop",
    "kenyan traditional",
    "keroncong",
    "khaliji",
    "khmer",
    "kids dance party",
    "kikuyu gospel",
    "kikuyu pop",
    "kinderchor",
    "kindermusik",
    "kindie rock",
    "kingston on indie",
    "kirtan",
    "kiwi rock",
    "kizomba",
    "klapa",
    "kleine hoerspiel",
    "kleinkunst",
    "klezmer",
    "knoxville indie",
    "kodomo no ongaku",
    "kolsche karneval",
    "komedi",
    "kompa",
    "kora",
    "korean classical performance",
    "korean contemporary classical",
    "korean electronic",
    "korean experimental",
    "korean indie rock",
    "korean jazz",
    "korean metal",
    "korean pop",
    "korean punk",
    "korean r&b",
    "korean traditional",
    "korean trap",
    "korean worship",
    "kosovan folk",
    "kosovan pop",
    "koto",
    "krautrock",
    "kritika",
    "kuduro",
    "kundiman",
    "kurdish folk",
    "kurdish pop",
    "kwaito",
    "kwaito house",
    "kyrgyz pop",
    "kyrgyz traditional",
    "la indie",
    "la pop",
    "laboratorio",
    "lafayette indie",
    "laiko",
    "lancashire indie",
    "lancaster pa indie",
    "landler",
    "language",
    "lao traditional",
    "late romantic era",
    "latin",
    "latin afrobeat",
    "latin alternative",
    "latin american baroque",
    "latin american heavy psych",
    "latin arena pop",
    "latin christian",
    "latin classical",
    "latin funk",
    "latin hip hop",
    "latin house",
    "latin jazz",
    "latin metal",
    "latin pop",
    "latin rock",
    "latin shoegaze",
    "latin ska",
    "latin soundtrack",
    "latin surf rock",
    "latin talent show",
    "latin tech house",
    "latin viral pop",
    "latin worship",
    "latincore",
    "latino comedy",
    "latintronica",
    "latvian folk",
    "latvian hip hop",
    "latvian indie",
    "latvian metal",
    "latvian pop",
    "latvian rock",
    "lawrence ks indie",
    "lds",
    "lds youth",
    "lebanese indie",
    "lebanese pop",
    "leeds indie",
    "leicester indie",
    "leipzig electronic",
    "leipzig indie",
    "leon gto indie",
    "lesen",
    "lesotho traditional",
    "levenslied",
    "lexington ky indie",
    "lezginka",
    "lgbtq+ hip hop",
    "liberian pop",
    "library music",
    "liechtenstein",
    "liedermacher",
    "light music",
    "lilith",
    "limerick indie",
    "lincoln ne indie",
    "liquid funk",
    "lithuanian electronic",
    "lithuanian folk",
    "lithuanian hip hop",
    "lithuanian indie",
    "lithuanian metal",
    "lithuanian pop",
    "lithuanian rock",
    "liverpool indie",
    "livetronica",
    "lldm",
    "lo star",
    "lo-fi",
    "lo-fi beats",
    "lo-fi chill",
    "lo-fi house",
    "london indie",
    "london on indie",
    "london rap",
    "louisiana blues",
    "louisiana metal",
    "louisville indie",
    "lounge",
    "lounge house",
    "louvor",
    "lovecraftian metal",
    "lovers rock",
    "lowercase",
    "luk thung",
    "lullaby",
    "lund indie",
    "lute",
    "luxembourgian hip hop",
    "luxembourgian indie",
    "macedonian electronic",
    "macedonian folk",
    "macedonian indie",
    "macedonian pop",
    "madchester",
    "maghreb",
    "magyar",
    "magyar alternative",
    "magyar mulatos",
    "magyar trap",
    "mahraganat",
    "maine indie",
    "mainland chinese pop",
    "makina",
    "makossa",
    "malagasy folk",
    "malawian pop",
    "malayalam hip hop",
    "malayalam worship",
    "malaysian hip hop",
    "malaysian indie",
    "malaysian mandopop",
    "malaysian metal",
    "malaysian pop",
    "malaysian tamil pop",
    "malian blues",
    "malian traditional",
    "mallet",
    "malmo indie",
    "maloya",
    "maltese pop",
    "mambo",
    "manchester hip hop",
    "manchester indie",
    "mande pop",
    "mandible",
    "mandolin",
    "mandopop",
    "manele",
    "mangue bit",
    "manila sound",
    "manitoba country",
    "manitoba indie",
    "manso indie",
    "mantra",
    "marathi pop",
    "marcha funebre",
    "marching band",
    "mariachi",
    "mariachi cristiano",
    "marimba de guatemala",
    "marimba mexicana",
    "marimba orquesta",
    "marrabenta",
    "martial industrial",
    "mashup",
    "maskandi",
    "massage",
    "math pop",
    "math rock",
    "math rock latinoamericano",
    "mathcore",
    "mathgrind",
    "mbalax",
    "mbira",
    "medieval",
    "medieval ensemble",
    "medieval folk",
    "medieval rock",
    "medimeisterschaften",
    "meditation",
    "medway sound",
    "melancholia",
    "melbourne bounce",
    "melbourne bounce international",
    "melbourne indie",
    "mellow gold",
    "melodic black metal",
    "melodic death metal",
    "melodic deathcore",
    "melodic dubstep",
    "melodic hard rock",
    "melodic hardcore",
    "melodic metal",
    "melodic metalcore",
    "melodic power metal",
    "melodic progressive metal",
    "melodic rap",
    "melodic techno",
    "melodic thrash",
    "melodipop",
    "meme rap",
    "memphis americana",
    "memphis blues",
    "memphis hip hop",
    "memphis indie",
    "memphis soul",
    "men's choir",
    "merengue",
    "merengue tipico",
    "merida indie",
    "merseybeat",
    "messianic praise",
    "mestissatge",
    "metal",
    "metal catala",
    "metal colombiano",
    "metal ecuatoriano",
    "metal galego",
    "metal gotico",
    "metal guitar",
    "metal noir quebecois",
    "metal paraguayo",
    "metal tico",
    "metal uruguayo",
    "metalcore",
    "metalcore espanol",
    "metallic hardcore",
    "metropopolis",
    "mevlevi sufi",
    "mexican black metal",
    "mexican classic rock",
    "mexican classical",
    "mexican edm",
    "mexican electronic",
    "mexican hardcore",
    "mexican hip hop",
    "mexican indie",
    "mexican metal",
    "mexican pop",
    "mexican pop punk",
    "mexican post-rock",
    "mexican rock",
    "mexican rock-and-roll",
    "mexican son",
    "mexican tech house",
    "mexican techno",
    "mexican traditional",
    "mezmur",
    "miami bass",
    "miami hip hop",
    "miami indie",
    "miami metal",
    "michigan folk",
    "michigan indie",
    "microhouse",
    "microtonal",
    "middle earth",
    "middle eastern traditional",
    "midwest americana",
    "midwest emo",
    "milan indie",
    "military band",
    "military cadence",
    "military rap",
    "milwaukee hip hop",
    "milwaukee indie",
    "min'yo",
    "mindfulness",
    "minecraft",
    "minimal dub",
    "minimal dubstep",
    "minimal melodic techno",
    "minimal synth",
    "minimal tech house",
    "minimal techno",
    "minimal wave",
    "minimalism",
    "minneapolis indie",
    "minneapolis punk",
    "minneapolis sound",
    "minnesota hip hop",
    "mississippi indie",
    "missouri indie",
    "mizrahi",
    "mluvene slovo",
    "mod revival",
    "modern alternative rock",
    "modern big band",
    "modern blues",
    "modern blues rock",
    "modern bollywood",
    "modern country rock",
    "modern downshift",
    "modern dream pop",
    "modern electroacoustic",
    "modern enka",
    "modern folk rock",
    "modern free jazz",
    "modern funk",
    "modern hard rock",
    "modern jazz piano",
    "modern jazz trio",
    "modern mod",
    "modern old-time",
    "modern performance",
    "modern power pop",
    "modern progressive rock",
    "modern psychedelic folk",
    "modern reggae",
    "modern rock",
    "modern salsa",
    "modern samba",
    "modern ska punk",
    "modern southern rock",
    "modern swing",
    "modern uplift",
    "modular synth",
    "modular techno",
    "molam",
    "moldovan pop",
    "mollywood",
    "monastic",
    "mongolian folk",
    "mongolian hip hop",
    "mongolian pop",
    "montana indie",
    "montenegrin pop",
    "monterrey indie",
    "montreal indie",
    "moog",
    "moombahton",
    "moravian folk",
    "morna",
    "moroccan pop",
    "moroccan traditional",
    "motivation",
    "motown",
    "mountain dulcimer",
    "movie tunes",
    "mpb",
    "mundart",
    "munich electronic",
    "munich indie",
    "murga",
    "music box",
    "music hall",
    "musica afroperuana",
    "musica antigua",
    "musica ayacuchana",
    "musica calabrese",
    "musica canaria",
    "musica colombiana instrumental",
    "musica de fondo",
    "musica de intervencao",
    "musica de pernambuco",
    "musica etnica",
    "musica folk asturiana",
    "musica infantil",
    "musica infantil catala",
    "musica jibara",
    "musica llanera",
    "musica lombarda",
    "musica mallorquina",
    "musica menorquina",
    "musica nativista",
    "musica occitana",
    "musica para ninos",
    "musica per bambini",
    "musica piemonteisa",
    "música pitiusa",
    "musica popular amazonense",
    "musica popular paraense",
    "musica portuguesa contemporanea",
    "musica potosina",
    "musica prehispanica",
    "musica rapa nui",
    "musica sarda",
    "musica valenciana",
    "musiikkia lapsille",
    "musik anak-anak",
    "musikkorps",
    "musique acadienne",
    "musique comorienne",
    "musique concrete",
    "musique guadeloupe",
    "musique mandingue",
    "musique peule",
    "musique pour enfant quebecois",
    "musique pour enfants",
    "musique soninke",
    "musique touareg",
    "musique traditionnelle comorienne",
    "muzica copii",
    "muzica crestina",
    "muzica populara",
    "muziek voor kinderen",
    "muzika l'yeladim",
    "naat",
    "naija worship",
    "namibian pop",
    "narodna muzika",
    "nasheed",
    "nashville americana",
    "nashville indie",
    "nashville singer-songwriter",
    "nashville sound",
    "nasyid",
    "native american",
    "native american flute",
    "native american hip hop",
    "native american spiritual",
    "navajo",
    "nc hip hop",
    "neapolitan funk",
    "necrogrind",
    "nederpop",
    "neo classical metal",
    "neo honky tonk",
    "neo kyma",
    "neo mellow",
    "neo metal",
    "neo r&b",
    "neo soul",
    "neo soul-jazz",
    "neo-classical",
    "neo-crust",
    "neo-industrial rock",
    "neo-kraut",
    "neo-pagan",
    "neo-progressive",
    "neo-proto",
    "neo-psychedelic",
    "neo-rockabilly",
    "neo-singer-songwriter",
    "neo-synthpop",
    "neo-trad doom metal",
    "neo-trad metal",
    "neo-trad prog",
    "neo-traditional bluegrass",
    "neo-traditional country",
    "neoclassical",
    "neofolk",
    "neomelodici",
    "neon pop punk",
    "neotango",
    "nepali indie",
    "nepali pop",
    "nephop",
    "nerdcore",
    "neue deutsche harte",
    "neue deutsche todeskunst",
    "neue deutsche welle",
    "neue volksmusik",
    "neurofunk",
    "neurostep",
    "new age",
    "new age piano",
    "new americana",
    "new beat",
    "new brunswick indie",
    "new comedy",
    "new england americana",
    "new french touch",
    "new hampshire indie",
    "new isolationism",
    "new jack smooth",
    "new jack swing",
    "new jersey hardcore",
    "new jersey indie",
    "new jersey punk",
    "new jersey rap",
    "new mexico music",
    "new orleans americana",
    "new orleans blues",
    "new orleans funk",
    "new orleans indie",
    "new orleans jazz",
    "new orleans rap",
    "new rave",
    "new romantic",
    "new tribe",
    "new wave",
    "new wave of glam metal",
    "new wave of speed metal",
    "new wave of thrash metal",
    "new wave pop",
    "new weird america",
    "new weird finland",
    "new zealand classical",
    "newcastle indie",
    "newcastle nsw indie",
    "newfoundland indie",
    "ngoni",
    "nica",
    "nice indie",
    "nigerian hip hop",
    "nigerian pop",
    "nightcore",
    "nightrun",
    "ninja",
    "nintendocore",
    "nisiotika",
    "nitzhonot",
    "nl folk",
    "no wave",
    "nohay",
    "noise",
    "noise pop",
    "noise punk",
    "noise rock",
    "noisecore",
    "nordic contemporary classical",
    "nordic folk",
    "nordic house",
    "nordic post-rock",
    "nordic soundtrack",
    "norges stemme",
    "normal indie",
    "norman ok indie",
    "norsk lovsang",
    "norteno",
    "norteno-sax",
    "north carolina emo",
    "north carolina indie",
    "north dakota indie",
    "north east england indie",
    "northamptonshire indie",
    "northern irish indie",
    "northern soul",
    "northumbrian folk",
    "norwegian alternative rock",
    "norwegian americana",
    "norwegian black metal",
    "norwegian blues",
    "norwegian choir",
    "norwegian classical",
    "norwegian contemporary jazz",
    "norwegian country",
    "norwegian death metal",
    "norwegian doom metal",
    "norwegian experimental",
    "norwegian folk",
    "norwegian gospel",
    "norwegian hardcore",
    "norwegian hip hop",
    "norwegian indie",
    "norwegian jazz",
    "norwegian metal",
    "norwegian pop",
    "norwegian pop rap",
    "norwegian prog",
    "norwegian psychedelic",
    "norwegian punk",
    "norwegian punk rock",
    "norwegian rock",
    "norwegian singer-songwriter",
    "norwegian space disco",
    "norwegian techno",
    "nottingham indie",
    "nouvelle chanson francaise",
    "nova canco",
    "nova mpb",
    "novelty",
    "novos talentos brasileiros",
    "nu age",
    "nu disco",
    "nu electro",
    "nu gaze",
    "nu jazz",
    "nu metal",
    "nu skool breaks",
    "nu-cumbia",
    "nu-metalcore",
    "nubian traditional",
    "nueva cancion",
    "nueva ola chilena",
    "nueva ola peruana",
    "nueva trova chilena",
    "nuevo folklore argentino",
    "nuevo tango",
    "nursery",
    "nwobhm",
    "nwocr",
    "nwothm",
    "ny roots",
    "nyahbinghi",
    "nyc pop",
    "nyc rap",
    "nyckelharpa",
    "nyhc",
    "nz christian",
    "nz electronic",
    "nz folk",
    "nz hardcore",
    "nz hip hop",
    "nz indie",
    "nz metal",
    "nz pop",
    "nz punk",
    "nz reggae",
    "nz singer-songwriter",
    "oakland indie",
    "oaxaca indie",
    "oberkrainer",
    "oceania soundtrack",
    "ohio indie",
    "oi",
    "ok indie",
    "okc indie",
    "okinawan folk",
    "okinawan pop",
    "oklahoma country",
    "oktoberfest",
    "old school dancehall",
    "old school hip hop",
    "old school nederhop",
    "old school thrash",
    "old school uk hip hop",
    "old west",
    "old-time",
    "old-time fiddle",
    "olympia wa indie",
    "omaha indie",
    "one-person band",
    "ontario indie",
    "opera",
    "opera chorus",
    "operatic pop",
    "operetta",
    "opm",
    "oratory",
    "orchestra",
    "orchestral performance",
    "organetto",
    "organic ambient",
    "organic electronic",
    "orgcore",
    "oriental classical",
    "oriental metal",
    "orkney and shetland folk",
    "orlando indie",
    "oromo pop",
    "orquesta cubana",
    "orquesta tipica",
    "orquesta tropical",
    "orquestas de galicia",
    "orthodox chant",
    "oshare kei",
    "oslo indie",
    "ostrock",
    "otacore",
    "oth indie",
    "ottawa indie",
    "ottawa rap",
    "oud",
    "oulu metal",
    "outer hip hop",
    "outlaw country",
    "outsider",
    "outsider house",
    "oxford indie",
    "oyun havasi",
    "p funk",
    "pagan black metal",
    "pagode",
    "pagode baiano",
    "paidika tragoudia",
    "pakistani folk",
    "pakistani indie",
    "pakistani pop",
    "palestinian pop",
    "palm desert scene",
    "panamanian indie",
    "panamanian pop",
    "panamanian rock",
    "panpipe",
    "papuan traditional",
    "papuri",
    "paracana",
    "paraguayan indie",
    "paraguayan rock",
    "parody",
    "partido alto",
    "partyschlager",
    "pasodobles",
    "pei indie",
    "pennsylvania hardcore",
    "permanent wave",
    "pernambuco alternative",
    "perreo",
    "persian alternative",
    "persian hip hop",
    "persian neo-traditional",
    "persian pop",
    "persian traditional",
    "perth indie",
    "peruvian death metal",
    "peruvian experimental",
    "peruvian hip hop",
    "peruvian indie",
    "peruvian metal",
    "peruvian punk",
    "peruvian rock",
    "pet calming",
    "philly indie",
    "philly rap",
    "philly soul",
    "phoenix indie",
    "phonk",
    "pianissimo",
    "piano blues",
    "piano cover",
    "piano mpb",
    "piano rock",
    "pibroch",
    "piedmont blues",
    "pilates",
    "pinoy alternative rap",
    "pinoy hip hop",
    "pinoy indie",
    "pinoy metal",
    "pinoy pop punk",
    "pinoy praise",
    "pinoy r&b",
    "pinoy reggae",
    "pinoy rock",
    "pinoy traditional",
    "pinoy trap",
    "pipa",
    "pirate",
    "pittsburgh indie",
    "pittsburgh rap",
    "pittsburgh rock",
    "pixie",
    "plunder",
    "png pop",
    "poetry",
    "poezja spiewana",
    "polca paraguaya",
    "police band",
    "polish alternative rock",
    "polish ambient",
    "polish black metal",
    "polish choir",
    "polish classical",
    "polish contemporary classical",
    "polish death metal",
    "polish early music",
    "polish electronica",
    "polish experimental",
    "polish experimental electronic",
    "polish folk",
    "polish free jazz",
    "polish hip hop",
    "polish indie",
    "polish jazz",
    "polish metal",
    "polish modern jazz",
    "polish pop",
    "polish post-rock",
    "polish punk",
    "polish reggae",
    "polish rock",
    "polish techno",
    "polish trap",
    "polish underground hip hop",
    "polka",
    "polynesian pop",
    "polynesian traditional",
    "polyphonies corses",
    "polyphony",
    "pony",
    "pop",
    "pop argentino",
    "pop catracho",
    "pop chileno",
    "pop edm",
    "pop emo",
    "pop flamenco",
    "pop folk",
    "pop house",
    "pop minang",
    "pop nacional",
    "pop paraguayo",
    "pop peruano",
    "pop punk",
    "pop quebecois",
    "pop rap",
    "pop reggaeton",
    "pop rock",
    "pop romantico",
    "pop urbaine",
    "pop violin",
    "popgaze",
    "popping",
    "popwave",
    "pornogrind",
    "porro",
    "portland hip hop",
    "portland indie",
    "portland metal",
    "portsmouth indie",
    "portuguese black metal",
    "portuguese contemporary classical",
    "portuguese death metal",
    "portuguese early music",
    "portuguese experimental",
    "portuguese folk",
    "portuguese indie",
    "portuguese indie rock",
    "portuguese jazz",
    "portuguese metal",
    "portuguese pop",
    "portuguese post-rock",
    "portuguese rock",
    "portuguese techno",
    "post-black metal",
    "post-disco",
    "post-disco soul",
    "post-doom metal",
    "post-grunge",
    "post-hardcore",
    "post-metal",
    "post-minimalism",
    "post-post-hardcore",
    "post-punk",
    "post-punk argentina",
    "post-punk brasileiro",
    "post-punk mexicano",
    "post-rock",
    "post-rock latinoamericano",
    "post-romantic era",
    "post-screamo",
    "post-teen pop",
    "power blues-rock",
    "power electronics",
    "power metal",
    "power noise",
    "power pop",
    "power thrash",
    "power-pop punk",
    "powerviolence",
    "powwow",
    "praise",
    "prank",
    "prepared piano",
    "preschool children's music",
    "prog metal",
    "prog quebec",
    "progressive alternative",
    "progressive black metal",
    "progressive bluegrass",
    "progressive breaks",
    "progressive deathcore",
    "progressive doom",
    "progressive electro house",
    "progressive house",
    "progressive jazz fusion",
    "progressive metal",
    "progressive metalcore",
    "progressive post-hardcore",
    "progressive power metal",
    "progressive psytrance",
    "progressive rock",
    "progressive sludge",
    "progressive technical death metal",
    "progressive thrash",
    "progressive trance",
    "progressive trance house",
    "progressive uplifting trance",
    "proto-rap",
    "proto-techno",
    "protopunk",
    "psalmen",
    "psybreaks",
    "psych gaze",
    "psychedelic blues-rock",
    "psychedelic doom",
    "psychedelic folk",
    "psychedelic folk rock",
    "psychedelic punk",
    "psychedelic rock",
    "psychedelic space rock",
    "psychedelic trance",
    "psychill",
    "psychobilly",
    "psychokore",
    "psytech",
    "pub rock",
    "puerto rican folk",
    "puerto rican indie",
    "puerto rican metal",
    "puerto rican pop",
    "puerto rican rock",
    "puglia indie",
    "punjabi folk",
    "punjabi pop",
    "punk",
    "punk blues",
    "punk catala",
    "punk colombiano",
    "punk euskera",
    "punk rock italiano",
    "punk ska",
    "punk tuga",
    "punk urbano",
    "punta",
    "purple sound",
    "qawwali",
    "quatuor a cordes",
    "quebec death metal",
    "quebec indie",
    "quebec punk",
    "queens hip hop",
    "queercore",
    "quiet storm",
    "quran",
    "r&b",
    "r&b argentino",
    "r&b brasileiro",
    "r&b en espanol",
    "rabindra sangeet",
    "radio symphony",
    "ragga jungle",
    "ragtime",
    "rai",
    "rajasthani folk",
    "rajasthani pop",
    "rakugo",
    "ranchera",
    "rap",
    "rap algerien",
    "rap antillais",
    "rap baiano",
    "rap calme",
    "rap catalan",
    "rap chileno",
    "rap conciencia",
    "rap conscient",
    "rap criolo",
    "rap cristao",
    "rap cristiano",
    "rap dominicano",
    "rap ecuatoriano",
    "rap euskera",
    "rap feminino nacional",
    "rap francais",
    "rap galego",
    "rap ivoire",
    "rap kreyol",
    "rap latina",
    "rap malien",
    "rap maroc",
    "rap maromba",
    "rap marseille",
    "rap metal",
    "rap metal espanol",
    "rap metalcore",
    "rap montrealais",
    "rap napoletano",
    "rap paraguayo",
    "rap rock",
    "rap salvadoreno",
    "rap sardegna",
    "rap toscana",
    "rap tunisien",
    "rap uruguayo",
    "rare groove",
    "rave",
    "raw black metal",
    "raw techno",
    "rawstyle",
    "re:techno",
    "reading",
    "reading indie",
    "rebel blues",
    "rebetiko",
    "recorder",
    "red dirt",
    "redneck",
    "reggae",
    "reggae catala",
    "reggae en espanol",
    "reggae fusion",
    "reggae mexicano",
    "reggae rock",
    "reggaeton",
    "reggaeton chileno",
    "reggaeton flow",
    "regional mexican",
    "regional mexican pop",
    "reiki",
    "relaxative",
    "remix product",
    "renaissance",
    "retro electro",
    "retro metal",
    "retro soul",
    "reunion pop",
    "rhode island indie",
    "rhythm and blues",
    "rhythm and boogie",
    "rhythm game",
    "riddim",
    "rif",
    "ringtone",
    "rio de la plata",
    "rio grande do sul indie",
    "riot grrrl",
    "ritmo kombina",
    "rochester mn indie",
    "rochester ny indie",
    "rock",
    "rock alternatif francais",
    "rock alternativo brasileiro",
    "rock alternativo espanol",
    "rock caipira",
    "rock catala",
    "rock catracho",
    "rock chapin",
    "rock cristiano",
    "rock curitibano",
    "rock en asturiano",
    "rock en espanol",
    "rock gaucho",
    "rock gospel brasileiro",
    "rock gotico",
    "rock kapak",
    "rock nacional",
    "rock nacional brasileiro",
    "rock noise",
    "rock progresivo mexicano",
    "rock quebecois",
    "rock steady",
    "rock tico",
    "rock urbano mexicano",
    "rock viet",
    "rock-and-roll",
    "rockabilly",
    "rockabilly en espanol",
    "roda de samba",
    "romanian contemporary classical",
    "romanian electronic",
    "romanian folk",
    "romanian hip hop",
    "romanian indie",
    "romanian metal",
    "romanian pop",
    "romanian rock",
    "romanian trap",
    "romantico",
    "rome indie",
    "rominimal",
    "roots americana",
    "roots reggae",
    "roots rock",
    "roots worship",
    "rosario indie",
    "rosary",
    "rotterdam indie",
    "rumba",
    "rumba catalana",
    "rumba congolaise",
    "rune folk",
    "russelater",
    "russian alternative",
    "russian black metal",
    "russian ccm",
    "russian chanson",
    "russian contemporary classical",
    "russian dance",
    "russian dance pop",
    "russian electronic",
    "russian emo",
    "russian experimental electronic",
    "russian folk",
    "russian gangster rap",
    "russian hip hop",
    "russian indie",
    "russian jazz",
    "russian metal",
    "russian modern classical",
    "russian pop",
    "russian post-punk",
    "russian post-rock",
    "russian punk",
    "russian reggae",
    "russian rock",
    "russian romance",
    "russian romanticism",
    "russian shoegaze",
    "russian synthpop",
    "russian techno",
    "russian trap",
    "russian underground rap",
    "ruta destroy",
    "rva indie",
    "rwandan hip hop",
    "rwandan pop",
    "rwandan traditional",
    "ryukoka",
    "ryukyu ongaku",
    "sacramento indie",
    "salay",
    "salsa",
    "salsa choke",
    "salsa colombiana",
    "salsa cristiana",
    "salsa cubana",
    "salsa international",
    "salsa peruana",
    "salsa puertorriquena",
    "salsa venezolana",
    "salzburg indie",
    "samba",
    "samba de roda",
    "samba reggae",
    "samba-enredo",
    "samba-rock",
    "sambass",
    "sami",
    "samoan pop",
    "san antonio indie",
    "san diego indie",
    "san diego rap",
    "san marcos tx indie",
    "sandalwood",
    "santa fe indie",
    "santur",
    "sarangi",
    "sardinia indie",
    "sarod",
    "saskatchewan indie",
    "scandinavian r&b",
    "scandipop",
    "schlager",
    "school choir",
    "school ensemble",
    "schranz",
    "schweizer rap",
    "sci-fi metal",
    "scorecore",
    "scottish americana",
    "scottish electronic",
    "scottish fiddle",
    "scottish folk",
    "scottish gaelic folk",
    "scottish hip hop",
    "scottish indie",
    "scottish indie folk",
    "scottish indie rock",
    "scottish jazz",
    "scottish metal",
    "scottish new wave",
    "scottish rock",
    "scottish singer-songwriter",
    "scottish techno",
    "scratch",
    "scream rap",
    "screamo",
    "screamocore",
    "seattle indie",
    "second line",
    "sefardi",
    "sega",
    "sega mauricien",
    "semba",
    "senegalese traditional",
    "serbian alternative rock",
    "serbian electronic",
    "serbian folk",
    "serbian metal",
    "serialism",
    "sertanejo",
    "sertanejo gospel",
    "sertanejo pop",
    "sertanejo tradicional",
    "sertanejo universitario",
    "sevdah",
    "sevilla indie",
    "sevillanas",
    "shaabi",
    "shabad",
    "shakuhachi",
    "shamanic",
    "shamisen",
    "shanty",
    "shantykoren",
    "sheffield indie",
    "sheilat",
    "shibuya-kei",
    "shimmer pop",
    "shimmer psych",
    "shiver pop",
    "shoegaze",
    "sholawat",
    "show tunes",
    "shred",
    "siberian folk",
    "sinaloa indie",
    "singaporean electronic",
    "singaporean hip hop",
    "singaporean indie",
    "singaporean mandopop",
    "singaporean metal",
    "singaporean pop",
    "singaporean singer-songwriter",
    "singer-songwriter",
    "singing bowl",
    "sinhala pop",
    "sinhala rap",
    "sinogaze",
    "sitar",
    "ska",
    "ska argentino",
    "ska catala",
    "ska espanol",
    "ska jazz",
    "ska mexicano",
    "ska punk",
    "ska revival",
    "skate punk",
    "skiffle",
    "skinhead oi",
    "skramz",
    "skweee",
    "sky room",
    "slack-key guitar",
    "slam death metal",
    "slam poetry",
    "slamming deathcore",
    "slash punk",
    "slavic folk metal",
    "slavic metal",
    "slayer",
    "slc indie",
    "sleaze rock",
    "sleep",
    "slovak electronic",
    "slovak folk",
    "slovak hip hop",
    "slovak indie",
    "slovak metal",
    "slovak pop",
    "slovak rock",
    "slovenian electronic",
    "slovenian folk",
    "slovenian indie",
    "slovenian metal",
    "slovenian pop",
    "slovenian rock",
    "slow core",
    "slow game",
    "sludge metal",
    "sludgecore",
    "small room",
    "smooth jazz",
    "smooth saxophone",
    "smooth soul",
    "smooth urban r&b",
    "soca",
    "socal pop punk",
    "social media pop",
    "soda pop",
    "soft rock",
    "solipsynthm",
    "somali pop",
    "somatik techno",
    "son cubano",
    "son cubano clasico",
    "song poem",
    "sonora indie",
    "soukous",
    "soul",
    "soul blues",
    "soul flow",
    "soul jazz",
    "sound",
    "sound art",
    "sound effects",
    "sound team",
    "soundtrack",
    "south african alternative",
    "south african choral",
    "south african country",
    "south african electronic",
    "south african gospel",
    "south african hip hop",
    "south african jazz",
    "south african metal",
    "south african pop",
    "south african punk",
    "south african rock",
    "south carolina indie",
    "south dakota indie",
    "south sudanese pop",
    "southampton indie",
    "southeast asian post-rock",
    "southern americana",
    "southern gospel",
    "southern hip hop",
    "southern metal",
    "southern rock",
    "southern soul",
    "southern soul blues",
    "soviet synthpop",
    "sovietwave",
    "spa",
    "space age pop",
    "space ambient",
    "space rock",
    "spacewave",
    "spanish baroque",
    "spanish black metal",
    "spanish blues",
    "spanish classical",
    "spanish contemporary classical",
    "spanish electropop",
    "spanish folk",
    "spanish folk metal",
    "spanish hip hop",
    "spanish indie pop",
    "spanish indie rock",
    "spanish invasion",
    "spanish jazz",
    "spanish metal",
    "spanish modern rock",
    "spanish new wave",
    "spanish noise pop",
    "spanish pop",
    "spanish pop rock",
    "spanish post-punk",
    "spanish post-rock",
    "spanish prog",
    "spanish progressive rock",
    "spanish psychedelic rock",
    "spanish punk",
    "spanish reggae",
    "spanish renaissance",
    "spanish rock",
    "spanish rockabilly",
    "spanish stoner rock",
    "spanish techno",
    "speed garage",
    "speed metal",
    "speedcore",
    "spiritual jazz",
    "spoken word",
    "springfield mo indie",
    "spytrack",
    "st petersburg fl indie",
    "starogradska",
    "steampunk",
    "steel guitar",
    "steelpan",
    "stl indie",
    "stockholm indie",
    "stomp and flutter",
    "stomp and holler",
    "stomp and whittle",
    "stomp pop",
    "stoner metal",
    "stoner rock",
    "straight edge",
    "straight-ahead jazz",
    "streektaal",
    "street band",
    "street punk",
    "street punk espanol",
    "stride",
    "string band",
    "string folk",
    "string orchestra",
    "string quartet",
    "strut",
    "stubenmusik",
    "stuttgart indie",
    "substep",
    "sudanese pop",
    "sufi",
    "sufi chant",
    "sundanese traditional",
    "sung poetry",
    "sungura",
    "sunset lounge",
    "sunshine pop",
    "suomi rock",
    "suomisaundi",
    "surf music",
    "surinamese pop",
    "swahili gospel",
    "swamp blues",
    "swamp pop",
    "swancore",
    "swansea indie",
    "swedish alternative rock",
    "swedish americana",
    "swedish black metal",
    "swedish blues",
    "swedish choir",
    "swedish classical",
    "swedish contemporary classical",
    "swedish country",
    "swedish dancehall",
    "swedish death metal",
    "swedish doom metal",
    "swedish electronic",
    "swedish electropop",
    "swedish eurodance",
    "swedish fiddle",
    "swedish folk pop",
    "swedish gangsta rap",
    "swedish garage rock",
    "swedish grindcore",
    "swedish hard rock",
    "swedish hardcore",
    "swedish hip hop",
    "swedish idol pop",
    "swedish indie pop",
    "swedish indie rock",
    "swedish jazz",
    "swedish jazz orkester",
    "swedish metal",
    "swedish metalcore",
    "swedish pop",
    "swedish pop punk",
    "swedish post-hardcore",
    "swedish post-punk",
    "swedish power metal",
    "swedish prog",
    "swedish psychedelic rock",
    "swedish punk",
    "swedish reggae",
    "swedish rockabilly",
    "swedish singer-songwriter",
    "swedish soul",
    "swedish stoner rock",
    "swedish synth",
    "swedish synthpop",
    "swedish techno",
    "swedish trap",
    "swedish tropical house",
    "swedish underground rap",
    "swedish urban",
    "swing",
    "swing italiano",
    "swing revival",
    "swiss alternative rock",
    "swiss contemporary classical",
    "swiss country",
    "swiss experimental",
    "swiss folk",
    "swiss hip hop",
    "swiss house",
    "swiss indie",
    "swiss indie folk",
    "swiss jazz",
    "swiss metal",
    "swiss pop",
    "swiss reggae",
    "swiss rock",
    "swiss singer-songwriter",
    "swiss techno",
    "swiss trap",
    "swiss worship",
    "sydney indie",
    "symphonic black metal",
    "symphonic death metal",
    "symphonic metal",
    "symphonic power metal",
    "symphonic rock",
    "synth punk",
    "synthpop",
    "syrian pop",
    "syro-aramaic chant",
    "szanty",
    "tabla",
    "tagalog worship",
    "tahitian",
    "taiko",
    "taiwan campus folk",
    "taiwan electronic",
    "taiwan experimental",
    "taiwan hip hop",
    "taiwan indie",
    "taiwan instrumental",
    "taiwan metal",
    "taiwan pop",
    "taiwan punk",
    "taiwan rock",
    "taiwan singer-songwriter",
    "taiwanese indigenous",
    "taiwanese pop",
    "tajik pop",
    "tajik traditional",
    "talent show",
    "talentos brasileiros",
    "tallava",
    "tamborazo",
    "tamburica",
    "tamil hip hop",
    "tamil pop",
    "tamil worship",
    "tampa indie",
    "tanci",
    "tango",
    "tango cancion",
    "tanzanian traditional",
    "tanzlmusi",
    "tar",
    "taraneem",
    "tarantella",
    "tassie indie",
    "tavern",
    "tech house",
    "technical black metal",
    "technical brutal death metal",
    "technical death metal",
    "technical deathcore",
    "technical groove",
    "technical thrash",
    "techno",
    "techno argentina",
    "techno kayo",
    "tecnobrega",
    "teen pop",
    "tejano",
    "tekno",
    "telugu worship",
    "tennessee metal",
    "terrorcore",
    "tex-mex",
    "texas blues",
    "texas country",
    "texas pop punk",
    "texas punk",
    "thai folk",
    "thai folk pop",
    "thai folk rock",
    "thai hip hop",
    "thai idol",
    "thai indie",
    "thai indie pop",
    "thai indie rock",
    "thai instrumental",
    "thai metal",
    "thai pop",
    "thai rock",
    "thai traditional",
    "thall",
    "theme",
    "therapy",
    "theremin",
    "thrash core",
    "thrash metal",
    "thrash-groove metal",
    "throat singing",
    "tibetan mantra",
    "tibetan pop",
    "tibetan traditional",
    "tico",
    "tijuana electronic",
    "tijuana indie",
    "timba",
    "tin pan alley",
    "tipico",
    "togolese pop",
    "tollywood",
    "tone",
    "tongan pop",
    "torch song",
    "toronto indie",
    "toronto rap",
    "trad jazz catala",
    "trad quebecois",
    "traditional bluegrass",
    "traditional blues",
    "traditional british folk",
    "traditional country",
    "traditional english folk",
    "traditional folk",
    "traditional funk",
    "traditional reggae",
    "traditional rockabilly",
    "traditional scottish folk",
    "traditional ska",
    "traditional soul",
    "trallalero",
    "trance",
    "trancecore",
    "transpop",
    "trap",
    "trap argentino",
    "trap brasileiro",
    "trap catala",
    "trap chileno",
    "trap espanol",
    "trap italiana",
    "trap latino",
    "trap metal italiana",
    "trap mexicano",
    "trap pesado",
    "trap queen",
    "trap soul",
    "trap tuga",
    "traprun",
    "trash rock",
    "trekkspill",
    "triangle indie",
    "tribal house",
    "tribute",
    "trikiti",
    "trinidadian reggae",
    "trio batak",
    "trio cubano",
    "trio huasteco",
    "trip hop",
    "trival",
    "trondheim indie",
    "tropical",
    "tropical house",
    "trova",
    "truck-driving country",
    "tucson indie",
    "tulsa indie",
    "tunisian pop",
    "turbo folk",
    "turin indie",
    "turkish alternative",
    "turkish alternative rock",
    "turkish black metal",
    "turkish classical",
    "turkish edm",
    "turkish electronic",
    "turkish experimental",
    "turkish folk",
    "turkish hip hop",
    "turkish instrumental",
    "turkish jazz",
    "turkish metal",
    "turkish modern jazz",
    "turkish pop",
    "turkish psych",
    "turkish punk",
    "turkish rock",
    "turkish singer-songwriter",
    "turkish soundtrack",
    "turkish trap",
    "turkish trap pop",
    "turntablism",
    "twee indie pop",
    "twee pop",
    "twin cities indie",
    "twoubadou",
    "tzadik",
    "uae indie",
    "ugandan pop",
    "ugandan traditional",
    "uilleann pipes",
    "uk alternative hip hop",
    "uk alternative pop",
    "uk americana",
    "uk beatdown",
    "uk christian rap",
    "uk contemporary jazz",
    "uk contemporary r&b",
    "uk dance",
    "uk dancehall",
    "uk diy punk",
    "uk dnb",
    "uk doom metal",
    "uk drill",
    "uk dub",
    "uk experimental electronic",
    "uk funky",
    "uk garage",
    "uk hip hop",
    "uk house",
    "uk metalcore",
    "uk noise rock",
    "uk pop",
    "uk pop punk",
    "uk post-hardcore",
    "uk post-metal",
    "uk post-punk",
    "uk post-punk revival",
    "uk reggae",
    "uk rockabilly",
    "uk stoner rock",
    "uk tech house",
    "uk worship",
    "ukg revival",
    "ukhc",
    "ukrainian black metal",
    "ukrainian choir",
    "ukrainian classical",
    "ukrainian electronic",
    "ukrainian experimental",
    "ukrainian folk",
    "ukrainian hip hop",
    "ukrainian indie",
    "ukrainian metal",
    "ukrainian pop",
    "ukrainian rock",
    "ukulele",
    "umbanda",
    "umea indie",
    "unblack metal",
    "underground hip hop",
    "underground latin hip hop",
    "underground power pop",
    "underground rap",
    "university choir",
    "uplifting trance",
    "uptempo hardcore",
    "urban contemporary",
    "uruguayan indie",
    "usbm",
    "utah indie",
    "uwielbienie",
    "uyghur folk",
    "uzbek pop",
    "uzbek traditional",
    "v-pop",
    "vaikiskos dainos",
    "vallenato",
    "vancouver indie",
    "vancouver metal",
    "vancouver punk",
    "vapor house",
    "vapor pop",
    "vapor soul",
    "vapor trap",
    "vapor twitch",
    "vaporwave",
    "vaqueiro",
    "variete francaise",
    "vaudeville",
    "vbs",
    "veena",
    "vegan straight edge",
    "vegas indie",
    "velha guarda",
    "venezuelan hip hop",
    "venezuelan indie",
    "venezuelan metal",
    "venezuelan rock",
    "veracruz indie",
    "vermont indie",
    "via",
    "victoria bc indie",
    "victorian britain",
    "video game music",
    "vienna indie",
    "vietnamese bolero",
    "vietnamese hip hop",
    "vietnamese pop",
    "vietnamese traditional",
    "viking folk",
    "viking metal",
    "villancicos",
    "vintage chanson",
    "vintage chinese pop",
    "vintage classical singing",
    "vintage country folk",
    "vintage dutch pop",
    "vintage french electronic",
    "vintage gospel",
    "vintage hawaiian",
    "vintage hollywood",
    "vintage italian soundtrack",
    "vintage jazz",
    "vintage old-time",
    "vintage radio show",
    "vintage reggae",
    "vintage rockabilly",
    "vintage schlager",
    "vintage spanish pop",
    "vintage swedish pop",
    "vintage swing",
    "vintage swoon",
    "vintage tango",
    "vintage western",
    "viol",
    "viola",
    "viola caipira",
    "violao",
    "violin",
    "viral pop",
    "viral trap",
    "virgin islands reggae",
    "virginia indie",
    "virginia metal",
    "virginia punk",
    "vispop",
    "visual kei",
    "vlaamse cabaret",
    "vlaamse kinderliedje",
    "vocal ensemble",
    "vocal harmony group",
    "vocal house",
    "vocal jazz",
    "vocal trance",
    "vocaloid",
    "vogue",
    "voidgaze",
    "voidgrind",
    "volksmusik",
    "volkspop",
    "volkstumliche musik",
    "waiata maori",
    "wandelweiser",
    "war metal",
    "warm drone",
    "warrington indie",
    "washboard",
    "washington indie",
    "wassoulou",
    "water",
    "wave",
    "weightless",
    "wellington indie",
    "welsh choir",
    "welsh folk",
    "welsh hip hop",
    "welsh indie",
    "welsh metal",
    "welsh rock",
    "west african jazz",
    "west australian hip hop",
    "west coast rap",
    "west coast reggae",
    "west coast trap",
    "west end",
    "west virginia indie",
    "west virginia metal",
    "west yorkshire indie",
    "west-vlaamse hip hop",
    "western americana",
    "western mass indie",
    "western saharan folk",
    "western swing",
    "white noise",
    "wind ensemble",
    "wind quintet",
    "windsor on indie",
    "winnipeg hip hop",
    "wisconsin indie",
    "witch house",
    "women's choir",
    "wonky",
    "workout product",
    "world",
    "world chill",
    "world fusion",
    "world meditation",
    "world worship",
    "worship",
    "wrestling",
    "wrock",
    "wu fam",
    "wyoming indie",
    "wyoming roots",
    "xhosa",
    "yacht rock",
    "ye ye",
    "yemeni traditional",
    "yiddish folk",
    "yodeling",
    "yoga",
    "yoik",
    "york indie",
    "yugoslav new wave",
    "yugoslav rock",
    "yunnan traditional",
    "zambian pop",
    "zampogna",
    "zapstep",
    "zen",
    "zespol dzieciecy",
    "zeuhl",
    "zhongguo feng",
    "zikir",
    "zillertal",
    "zim gospel",
    "zim hip hop",
    "zim urban groove",
    "zimdancehall",
    "zither",
    "zolo",
    "zouglou",
    "zouk",
    "zouk riddim",
    "zurich indie",
    "zydeco"
  ];

  var _currentGenre; // = _genres[0];

  List<String> get genres {
    return _genres;
  }

  String get currentGenre {
    return _currentGenre;
  }

  void setCurrentGenre(newGenre) {
    _currentGenre = newGenre;
    notifyListeners();
  }
}
